// Sparsity-aware attention testbench (Step 6)
// Tests element-level (B1) and row-level (B2) sparsity.
// Uses randomly generated Q/K data with computed thresholds.

`timescale 1ns / 1ps

module sparsity_tb;

  parameter int TOTAL_CYCLE = 8;
  parameter int BW = 8;
  parameter int BW_PSUM = 2 * BW + 4;
  parameter int PR = 16;
  parameter int COL = 8;
  parameter int MCP = 4;

  integer qk_file;
  integer qk_scan_file;
  integer captured_data;

  integer K[COL-1:0][PR-1:0];
  integer Q[TOTAL_CYCLE-1:0][PR-1:0];
  integer result[TOTAL_CYCLE-1:0][COL-1:0];
  integer sum[TOTAL_CYCLE-1:0];
  integer abs_result[TOTAL_CYCLE-1:0][COL-1:0];
  integer norm_result[TOTAL_CYCLE-1:0][COL-1:0];

  // Sparsity tracking
  integer gated_count;
  integer total_count;
  integer skipped_rows;

  integer i, j, k, t, p, q, s, u, m;

  logic reset = 1;
  logic clk = 0;
  logic [PR*BW-1:0] mem_in;
  logic ofifo_rd = 0;
  logic [16:0] inst;
  logic qmem_rd = 0;
  logic qmem_wr = 0;
  logic kmem_rd = 0;
  logic kmem_wr = 0;
  logic pmem_rd = 0;
  logic pmem_wr = 0;
  logic execute = 0;
  logic load = 0;
  logic [3:0] qkmem_add = 0;
  logic [3:0] pmem_add = 0;

  // Sparsity controls
  logic enable_elem_sparsity = 0;
  logic [BW_PSUM-1:0] threshold_elem = 0;
  logic enable_row_sparsity = 0;
  logic [BW_PSUM+3:0] threshold_row = 0;

  logic [BW_PSUM*COL-1:0] out;
  logic div_ready_out;

  always_comb begin
    inst[16]    = ofifo_rd;
    inst[15:12] = qkmem_add;
    inst[11:8]  = pmem_add;
    inst[7]     = execute;
    inst[6]     = load;
    inst[5]     = qmem_rd;
    inst[4]     = qmem_wr;
    inst[3]     = kmem_rd;
    inst[2]     = kmem_wr;
    inst[1]     = pmem_rd;
    inst[0]     = pmem_wr;
  end

  logic [BW_PSUM-1:0] temp5b;
  logic [BW_PSUM*COL-1:0] temp16b;

  core #(
      .BW(BW),
      .BW_PSUM(BW_PSUM),
      .COL(COL),
      .PR(PR)
  ) core_instance (
      .reset(reset),
      .clk(clk),
      .mem_in(mem_in),
      .inst(inst),
      .out(out),
      .sum_in({(BW_PSUM + 4) {1'b0}}),
      .fifo_ext_rd(1'b0),
      .sum_out(),
      .div_ready(div_ready_out),
      .enable_elem_sparsity(enable_elem_sparsity),
      .threshold_elem(threshold_elem),
      .enable_row_sparsity(enable_row_sparsity),
      .threshold_row(threshold_row)
  );

  initial begin

    $dumpfile("sparsity_tb.vcd");
    $dumpvars(0, sparsity_tb);

    //=============================================================
    // Read data from files generated by gen_sparsity_data.py
    //=============================================================

    // Read Q data
    qk_file = $fopen("sparsity_qdata.txt", "r");
    for (q = 0; q < TOTAL_CYCLE; q = q + 1) begin
      for (j = 0; j < PR; j = j + 1) begin
        qk_scan_file = $fscanf(qk_file, "%d\n", captured_data);
        Q[q][j] = captured_data;
      end
    end
    $fclose(qk_file);

    // Read K data
    qk_file = $fopen("sparsity_kdata.txt", "r");
    for (q = 0; q < COL; q = q + 1) begin
      for (j = 0; j < PR; j = j + 1) begin
        qk_scan_file = $fscanf(qk_file, "%d\n", captured_data);
        K[q][j] = captured_data;
      end
    end
    $fclose(qk_file);

    // Read thresholds
    qk_file = $fopen("sparsity_thresholds.txt", "r");
    qk_scan_file = $fscanf(qk_file, "%d\n", captured_data);
    threshold_elem = captured_data;
    qk_scan_file = $fscanf(qk_file, "%d\n", captured_data);
    threshold_row = captured_data;
    $fclose(qk_file);

    $display("===== Sparsity-Aware Attention Test =====");
    $display("Element threshold: %0d", threshold_elem);
    $display("Row threshold: %0d", threshold_row);

    //=============================================================
    // Compute expected results in testbench
    //=============================================================
    $display("##### Expected results #####");

    gated_count  = 0;
    total_count  = 0;
    skipped_rows = 0;

    for (t = 0; t < TOTAL_CYCLE; t = t + 1) begin
      sum[t] = 0;
      for (q = 0; q < COL; q = q + 1) begin
        result[t][q] = 0;
        for (k = 0; k < PR; k = k + 1) begin
          result[t][q] = result[t][q] + Q[t][k] * K[q][k];
        end

        if (result[t][q] < 0) abs_result[t][q] = -result[t][q];
        else abs_result[t][q] = result[t][q];

        // B1: element-level sparsity check
        total_count = total_count + 1;
        if (abs_result[t][q] < threshold_elem) begin
          gated_count = gated_count + 1;
        end

        sum[t] = sum[t] + abs_result[t][q];
      end

      // B2: row-level sparsity check
      if (sum[t] < threshold_row) begin
        skipped_rows = skipped_rows + 1;
        $display("Row %0d: sum=%0d < threshold=%0d -> SKIP normalization", t, sum[t],
                 threshold_row);
      end else begin
        for (q = 0; q < COL; q = q + 1) begin
          if (sum[t] != 0) norm_result[t][q] = result[t][q] / (sum[t] >> 7);
          else norm_result[t][q] = 0;
        end
      end
    end

    $display("Element sparsity: %0d/%0d gated (%.1f%%)", gated_count, total_count,
             100.0 * gated_count / total_count);
    $display("Row sparsity: %0d/%0d rows skipped (%.1f%%)", skipped_rows, TOTAL_CYCLE,
             100.0 * skipped_rows / TOTAL_CYCLE);

    //=============================================================
    // Run 3 configurations: baseline, B1 only, B1+B2
    //=============================================================

    //--- Configuration 1: Baseline (no sparsity) ---
    $display("\n===== Config 1: Baseline (no sparsity) =====");
    enable_elem_sparsity = 0;
    enable_row_sparsity  = 0;

    // Reset
    for (q = 0; q < 2; q = q + 1) begin
      #0.5 clk = 1'b0;
      #0.5 clk = 1'b1;
    end
    for (q = 0; q < 10; q = q + 1) begin
      #0.5 clk = 1'b0;
      #0.5 clk = 1'b1;
    end
    reset = 0;

    // Load Q, K, execute, normalize (same as fullchip_tb)
    // Qmem write
    for (q = 0; q < TOTAL_CYCLE; q = q + 1) begin
      #0.5 clk = 1'b0;
      qmem_wr = 1;
      if (q > 0) qkmem_add = qkmem_add + 1;
      for (j = 0; j < PR; j = j + 1) mem_in[BW*(j+1)-1-:BW] = Q[q][j];
      #0.5 clk = 1'b1;
    end
    #0.5 clk = 1'b0;
    qmem_wr   = 0;
    qkmem_add = 0;
    #0.5 clk = 1'b1;

    // Kmem write
    for (q = 0; q < COL; q = q + 1) begin
      #0.5 clk = 1'b0;
      kmem_wr = 1;
      if (q > 0) qkmem_add = qkmem_add + 1;
      for (j = 0; j < PR; j = j + 1) mem_in[BW*(j+1)-1-:BW] = K[q][j];
      #0.5 clk = 1'b1;
    end
    #0.5 clk = 1'b0;
    kmem_wr   = 0;
    qkmem_add = 0;
    #0.5 clk = 1'b1;

    for (q = 0; q < 2; q = q + 1) begin
      #0.5 clk = 1'b0;
      #0.5 clk = 1'b1;
    end

    // K loading
    for (q = 0; q < COL + 1; q = q + 1) begin
      #0.5 clk = 1'b0;
      load = 1;
      if (q == 1) kmem_rd = 1;
      if (q > 1) qkmem_add = qkmem_add + 1;
      #0.5 clk = 1'b1;
    end
    #0.5 clk = 1'b0;
    kmem_rd   = 0;
    qkmem_add = 0;
    #0.5 clk = 1'b1;
    #0.5 clk = 1'b0;
    load = 0;
    #0.5 clk = 1'b1;

    for (q = 0; q < 10; q = q + 1) begin
      #0.5 clk = 1'b0;
      #0.5 clk = 1'b1;
    end

    // Execute
    for (q = 0; q < TOTAL_CYCLE; q = q + 1) begin
      #0.5 clk = 1'b0;
      execute = 1;
      qmem_rd = 1;
      if (q > 0) qkmem_add = qkmem_add + 1;
      #0.5 clk = 1'b1;
    end
    #0.5 clk = 1'b0;
    qmem_rd   = 0;
    qkmem_add = 0;
    execute   = 0;
    #0.5 clk = 1'b1;

    for (q = 0; q < 10; q = q + 1) begin
      #0.5 clk = 1'b0;
      #0.5 clk = 1'b1;
    end

    // Move ofifo to pmem
    for (q = 0; q < TOTAL_CYCLE; q = q + 1) begin
      #0.5 clk = 1'b0;
      ofifo_rd = 1;
      pmem_wr  = 1;
      if (q > 0) pmem_add = pmem_add + 1;
      #0.5 clk = 1'b1;
    end
    #0.5 clk = 1'b0;
    pmem_wr  = 0;
    pmem_add = 0;
    ofifo_rd = 0;
    #0.5 clk = 1'b1;

    for (q = 0; q < 5; q = q + 1) begin
      #0.5 clk = 1'b0;
      #0.5 clk = 1'b1;
    end

    // Accumulate
    for (q = 0; q < TOTAL_CYCLE; q = q + 1) begin
      #0.5 clk = 1'b0;
      pmem_rd = 1;
      execute = 1;
      load = 0;
      pmem_add = q;
      #0.5 clk = 1'b1;
    end
    #0.5 clk = 1'b0;
    pmem_rd  = 0;
    execute  = 0;
    pmem_add = 0;
    #0.5 clk = 1'b1;

    for (q = 0; q < 5; q = q + 1) begin
      #0.5 clk = 1'b0;
      #0.5 clk = 1'b1;
    end

    // Divide with MCP (Multi-Cycle Path)
    for (q = 0; q < TOTAL_CYCLE; q = q + 1) begin
      for (m = 0; m < MCP + 1; m = m + 1) begin
        #0.5 clk = 1'b0;
        pmem_rd = 1;
        pmem_wr = 1;
        load = 1;
        execute = 0;
        pmem_add = q;
        #0.5 clk = 1'b1;
      end
      #0.5 clk = 1'b0;
      pmem_rd = 0;
      pmem_wr = 0;
      load = 0;
      #0.5 clk = 1'b1;
    end

    for (q = 0; q < 5; q = q + 1) begin
      #0.5 clk = 1'b0;
      #0.5 clk = 1'b1;
    end

    // Read back results
    $display("Baseline results:");
    for (q = 0; q < TOTAL_CYCLE; q = q + 1) begin
      #0.5 clk = 1'b0;
      pmem_rd  = 1;
      pmem_add = q;
      #0.5 clk = 1'b1;
      #0.5 clk = 1'b0;
      #0.5 clk = 1'b1;
      $display("  baseline @cycle%2d: %40h", q, out);
    end
    #0.5 clk = 1'b0;
    pmem_rd  = 0;
    pmem_add = 0;
    #0.5 clk = 1'b1;

    //--- Configuration 2: B1 only (element-level sparsity) ---
    $display("\n===== Config 2: B1 (element-level sparsity) =====");
    // Reset and re-run with element sparsity enabled
    reset = 1;
    for (q = 0; q < 5; q = q + 1) begin
      #0.5 clk = 1'b0;
      #0.5 clk = 1'b1;
    end
    reset = 0;
    enable_elem_sparsity = 1;
    enable_row_sparsity = 0;

    // Repeat: Qmem, Kmem, load, execute, ofifo->pmem, acc, div, readback
    // Qmem write
    for (q = 0; q < TOTAL_CYCLE; q = q + 1) begin
      #0.5 clk = 1'b0;
      qmem_wr = 1;
      if (q > 0) qkmem_add = qkmem_add + 1;
      for (j = 0; j < PR; j = j + 1) mem_in[BW*(j+1)-1-:BW] = Q[q][j];
      #0.5 clk = 1'b1;
    end
    #0.5 clk = 1'b0;
    qmem_wr   = 0;
    qkmem_add = 0;
    #0.5 clk = 1'b1;
    for (q = 0; q < COL; q = q + 1) begin
      #0.5 clk = 1'b0;
      kmem_wr = 1;
      if (q > 0) qkmem_add = qkmem_add + 1;
      for (j = 0; j < PR; j = j + 1) mem_in[BW*(j+1)-1-:BW] = K[q][j];
      #0.5 clk = 1'b1;
    end
    #0.5 clk = 1'b0;
    kmem_wr   = 0;
    qkmem_add = 0;
    #0.5 clk = 1'b1;
    for (q = 0; q < 2; q = q + 1) begin
      #0.5 clk = 1'b0;
      #0.5 clk = 1'b1;
    end
    for (q = 0; q < COL + 1; q = q + 1) begin
      #0.5 clk = 1'b0;
      load = 1;
      if (q == 1) kmem_rd = 1;
      if (q > 1) qkmem_add = qkmem_add + 1;
      #0.5 clk = 1'b1;
    end
    #0.5 clk = 1'b0;
    kmem_rd   = 0;
    qkmem_add = 0;
    #0.5 clk = 1'b1;
    #0.5 clk = 1'b0;
    load = 0;
    #0.5 clk = 1'b1;
    for (q = 0; q < 10; q = q + 1) begin
      #0.5 clk = 1'b0;
      #0.5 clk = 1'b1;
    end
    for (q = 0; q < TOTAL_CYCLE; q = q + 1) begin
      #0.5 clk = 1'b0;
      execute = 1;
      qmem_rd = 1;
      if (q > 0) qkmem_add = qkmem_add + 1;
      #0.5 clk = 1'b1;
    end
    #0.5 clk = 1'b0;
    qmem_rd   = 0;
    qkmem_add = 0;
    execute   = 0;
    #0.5 clk = 1'b1;
    for (q = 0; q < 10; q = q + 1) begin
      #0.5 clk = 1'b0;
      #0.5 clk = 1'b1;
    end
    for (q = 0; q < TOTAL_CYCLE; q = q + 1) begin
      #0.5 clk = 1'b0;
      ofifo_rd = 1;
      pmem_wr  = 1;
      if (q > 0) pmem_add = pmem_add + 1;
      #0.5 clk = 1'b1;
    end
    #0.5 clk = 1'b0;
    pmem_wr  = 0;
    pmem_add = 0;
    ofifo_rd = 0;
    #0.5 clk = 1'b1;
    for (q = 0; q < 5; q = q + 1) begin
      #0.5 clk = 1'b0;
      #0.5 clk = 1'b1;
    end
    for (q = 0; q < TOTAL_CYCLE; q = q + 1) begin
      #0.5 clk = 1'b0;
      pmem_rd = 1;
      execute = 1;
      load = 0;
      pmem_add = q;
      #0.5 clk = 1'b1;
    end
    #0.5 clk = 1'b0;
    pmem_rd  = 0;
    execute  = 0;
    pmem_add = 0;
    #0.5 clk = 1'b1;
    for (q = 0; q < 5; q = q + 1) begin
      #0.5 clk = 1'b0;
      #0.5 clk = 1'b1;
    end
    for (q = 0; q < TOTAL_CYCLE; q = q + 1) begin
      for (m = 0; m < MCP + 1; m = m + 1) begin
        #0.5 clk = 1'b0;
        pmem_rd = 1;
        pmem_wr = 1;
        load = 1;
        execute = 0;
        pmem_add = q;
        #0.5 clk = 1'b1;
      end
      #0.5 clk = 1'b0;
      pmem_rd = 0;
      pmem_wr = 0;
      load = 0;
      #0.5 clk = 1'b1;
    end
    for (q = 0; q < 5; q = q + 1) begin
      #0.5 clk = 1'b0;
      #0.5 clk = 1'b1;
    end
    $display("B1 results:");
    for (q = 0; q < TOTAL_CYCLE; q = q + 1) begin
      #0.5 clk = 1'b0;
      pmem_rd  = 1;
      pmem_add = q;
      #0.5 clk = 1'b1;
      #0.5 clk = 1'b0;
      #0.5 clk = 1'b1;
      $display("  B1 @cycle%2d: %40h", q, out);
    end
    #0.5 clk = 1'b0;
    pmem_rd  = 0;
    pmem_add = 0;
    #0.5 clk = 1'b1;

    //--- Configuration 3: B1+B2 (element + row sparsity) ---
    $display("\n===== Config 3: B1+B2 (element + row sparsity) =====");
    reset = 1;
    for (q = 0; q < 5; q = q + 1) begin
      #0.5 clk = 1'b0;
      #0.5 clk = 1'b1;
    end
    reset = 0;
    enable_elem_sparsity = 1;
    enable_row_sparsity = 1;

    // Repeat full sequence
    for (q = 0; q < TOTAL_CYCLE; q = q + 1) begin
      #0.5 clk = 1'b0;
      qmem_wr = 1;
      if (q > 0) qkmem_add = qkmem_add + 1;
      for (j = 0; j < PR; j = j + 1) mem_in[BW*(j+1)-1-:BW] = Q[q][j];
      #0.5 clk = 1'b1;
    end
    #0.5 clk = 1'b0;
    qmem_wr   = 0;
    qkmem_add = 0;
    #0.5 clk = 1'b1;
    for (q = 0; q < COL; q = q + 1) begin
      #0.5 clk = 1'b0;
      kmem_wr = 1;
      if (q > 0) qkmem_add = qkmem_add + 1;
      for (j = 0; j < PR; j = j + 1) mem_in[BW*(j+1)-1-:BW] = K[q][j];
      #0.5 clk = 1'b1;
    end
    #0.5 clk = 1'b0;
    kmem_wr   = 0;
    qkmem_add = 0;
    #0.5 clk = 1'b1;
    for (q = 0; q < 2; q = q + 1) begin
      #0.5 clk = 1'b0;
      #0.5 clk = 1'b1;
    end
    for (q = 0; q < COL + 1; q = q + 1) begin
      #0.5 clk = 1'b0;
      load = 1;
      if (q == 1) kmem_rd = 1;
      if (q > 1) qkmem_add = qkmem_add + 1;
      #0.5 clk = 1'b1;
    end
    #0.5 clk = 1'b0;
    kmem_rd   = 0;
    qkmem_add = 0;
    #0.5 clk = 1'b1;
    #0.5 clk = 1'b0;
    load = 0;
    #0.5 clk = 1'b1;
    for (q = 0; q < 10; q = q + 1) begin
      #0.5 clk = 1'b0;
      #0.5 clk = 1'b1;
    end
    for (q = 0; q < TOTAL_CYCLE; q = q + 1) begin
      #0.5 clk = 1'b0;
      execute = 1;
      qmem_rd = 1;
      if (q > 0) qkmem_add = qkmem_add + 1;
      #0.5 clk = 1'b1;
    end
    #0.5 clk = 1'b0;
    qmem_rd   = 0;
    qkmem_add = 0;
    execute   = 0;
    #0.5 clk = 1'b1;
    for (q = 0; q < 10; q = q + 1) begin
      #0.5 clk = 1'b0;
      #0.5 clk = 1'b1;
    end
    for (q = 0; q < TOTAL_CYCLE; q = q + 1) begin
      #0.5 clk = 1'b0;
      ofifo_rd = 1;
      pmem_wr  = 1;
      if (q > 0) pmem_add = pmem_add + 1;
      #0.5 clk = 1'b1;
    end
    #0.5 clk = 1'b0;
    pmem_wr  = 0;
    pmem_add = 0;
    ofifo_rd = 0;
    #0.5 clk = 1'b1;
    for (q = 0; q < 5; q = q + 1) begin
      #0.5 clk = 1'b0;
      #0.5 clk = 1'b1;
    end
    for (q = 0; q < TOTAL_CYCLE; q = q + 1) begin
      #0.5 clk = 1'b0;
      pmem_rd = 1;
      execute = 1;
      load = 0;
      pmem_add = q;
      #0.5 clk = 1'b1;
    end
    #0.5 clk = 1'b0;
    pmem_rd  = 0;
    execute  = 0;
    pmem_add = 0;
    #0.5 clk = 1'b1;
    for (q = 0; q < 5; q = q + 1) begin
      #0.5 clk = 1'b0;
      #0.5 clk = 1'b1;
    end
    for (q = 0; q < TOTAL_CYCLE; q = q + 1) begin
      for (m = 0; m < MCP + 1; m = m + 1) begin
        #0.5 clk = 1'b0;
        pmem_rd = 1;
        pmem_wr = 1;
        load = 1;
        execute = 0;
        pmem_add = q;
        #0.5 clk = 1'b1;
      end
      #0.5 clk = 1'b0;
      pmem_rd = 0;
      pmem_wr = 0;
      load = 0;
      #0.5 clk = 1'b1;
    end
    for (q = 0; q < 5; q = q + 1) begin
      #0.5 clk = 1'b0;
      #0.5 clk = 1'b1;
    end
    $display("B1+B2 results:");
    for (q = 0; q < TOTAL_CYCLE; q = q + 1) begin
      #0.5 clk = 1'b0;
      pmem_rd  = 1;
      pmem_add = q;
      #0.5 clk = 1'b1;
      #0.5 clk = 1'b0;
      #0.5 clk = 1'b1;
      $display("  B1+B2 @cycle%2d: %40h", q, out);
    end
    #0.5 clk = 1'b0;
    pmem_rd  = 0;
    pmem_add = 0;
    #0.5 clk = 1'b1;

    $display("\n===== Sparsity Test Complete =====");
    #10 $finish;

  end

endmodule
